### ISSUE TITLE
The namespace already contains a definition for error codes

### ISSUE THREAD

**Issue by MichalTluczykontTDS** [Kaz-TDS/Response-Framework-Draft#4]
When we have two classes that implement the same interface there is an error:

![image](https://github.com/Kaz-TDS/Response-Framework-Draft/assets/129741437/ca742d18-3bff-4262-81ce-82f36a8a7264)

Case:

```
public interface MyInterface {
    Result<int> GetNumber();
}

public class Foo : MyInterface {
    [ErrorResult(123, "Something")]
    public Result<int> GetNumber(){
        throw new System.NotImplementedException();
    }
}

public class Bar : MyInterface {
    [ErrorResult(678, "Other error")]
    public Result<int> GetNumber(){
        throw new System.NotImplementedException();
    }
}
```

Expected result:
Have a possibility to use different errors for different implementations.

**Comment by Kaz-TDS** [comment]
Fixed the issue. Now error codes and error results are nested in the results providers which means that each class implementing an interface will have their own internal error result and error code holder class within their internal namespace removing the collisions
